---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver on ubuntu server
    apt:
      name: apache2
      state: present

  - name: to start the webserver on nodes
    service:
       name: apache2
       state: started  